### ISSUE TITLE
add some prerequisites in README.md

### ISSUE THREAD

**Issue by HamishB** [samiiali/adcirpolate#1]
Hi,

It would save some trouble & time for folks building the software on clusters with only older versions of software available if the Prerequisites section of README.md noted that cmake version >= 3 and Gfortran >= 4.9 (or another compiler supporting Fortran 2008 features) will be needed.

many thanks.

**Comment by samiiali** [comment]
Thank you @HamishB. I modified the readme file to address your comment. I have not been actively maintaining this repository, but at the time of developing Adcirpolate, I tested it on different clusters in [TACC](https://www.tacc.utexas.edu/) without any issues. I doubt we need Fortran 2008 support to compile the code.

**Comment by samiiali** [comment]
Closing this issue, as it is addressed in the latest version.
